-- 코드를 입력하세요
WITH RECURSIVE BLANK AS (SELECT 0 AS HOUR
                        UNION ALL
                        SELECT HOUR + 1
                        FROM BLANK
                        WHERE HOUR<23)

#SELECT * FROM BLANK

SELECT HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM BLANK B
LEFT JOIN ANIMAL_OUTS A ON B.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR