-- 코드를 입력하세요
SELECT B.author_id, B.author_name, A.category,
SUM(C.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE C.sales_date LIKE '2022-01%'
GROUP BY A.author_id, A.category
ORDER BY B.AUTHOR_ID, A.CATEGORY DESC